In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
from datetime import datetime
import plotly
plotly.tools.set_credentials_file(username='bzjin', api_key='jmaLQFWVMgugFAITZZBC')
import plotly.plotly as py
import plotly.graph_objs as go

#Sort function
def object_compare(x, y):
   if x.count > y.count:
      return 1
   elif x.count == y.count:
      return 0
   else:  
      return -1

In [20]:
# "offender_offenses_ccs.csv" has 414,617 rows x 17 columns
offenses = pd.read_csv("offender_offenses_ccs.csv")
first = offenses.iloc[0:10000,:]
reviews.head()

,DCNumber,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,ProbationTerm,ParoleTerm,adjudicationcharge_descr,qualifier_descr,adjudication_descr
0,000084,1,01/27/76 00:00:00,10/08/76 00:00:00,DUVAL,7600296.0,9999998,0,0,1ST DG MUR/PREMED. OR ATT.,PRINCIPAL,ADJUDICATION NOT WITHHELD
1,000256,1,01/29/71 00:00:00,10/12/71 00:00:00,LEON,6528.0,9999998,0,9999998,1ST DG MUR/PREMED. OR ATT.,PRINCIPAL,ADJUDICATION NOT WITHHELD
2,000256,2,08/17/90 00:00:00,12/21/90 00:00:00,LEON,9003492.0,70000,0,0,BURGUNOCCSTRUC/CV OR ATT.,PRINCIPAL,ADJUDICATION NOT WITHHELD
3,000316,1,10/15/59 00:00:00,12/04/59 00:00:00,MIAMI-DADE,5905444.0,150000,0,0,ROBBERY,PRINCIPAL,ADJUDICATION NOT WITHHELD
4,000316,2,01/15/62 00:00:00,02/02/62 00:00:00,BROWARD,6236552.0,20000,0,0,BURGUNOCCSTRUC/CV OR ATT.,PRINCIPAL IN ATTEMPT,ADJUDICATION NOT WITHHELD

In [22]:
#Charges
chargeSeries = pd.Series(first["adjudicationcharge_descr"])
chargeArray = np.array(chargeSeries, dtype=pd.Series)

unique, counts = np.unique(chargeArray, return_counts=True)
d = {}
for x in unique:
    d[x] = counts[np.where(unique==x)][0]

#chargedata=[go.Bar(x=unique, y=counts)]
#py.iplot(chargedata, filename='basic-bar')

In [21]:
# Offense classifications from http://www.dc.state.fl.us/OffenderSearch/offensecategory.aspx#ED
classifications = pd.read_csv("offense_classifications.csv", low_memory=False)
classifications.head()

   code                            name             category
0  1350                      3+ BATTERY  Assault and Battery
1  3840             ABUSE ELDER/DISABLD  Assault and Battery
2  3841         ABUSE ELDER/DISBLD-HARM  Assault and Battery
3  1318  AGG ASSLT-INTENT COMMIT FELONY  Assault and Battery
4  1317  AGG ASSLT-W/WPN NO INTENT TO K  Assault and Battery

In [52]:
class_dict = {}

cate_Series = pd.Series(classifications["category"])
cate_Array = np.array(cate_Series, dtype=pd.Series)
unique, counts = np.unique(cate_Array, return_counts=True)

for x in unique:
    class_dict[x] = 0

for x in classifications["name"]:
    category = str(classifications["category"])
    print(class_dict[category])
    #class_dict[category] = float(class_dict[category]) + d[x]
    
#print(class_dict)

KeyError: '0       Assault and Battery\n1       Assault and Battery\n2       Assault and Battery\n3       Assault and Battery\n4       Assault and Battery\n5       Assault and Battery\n6       Assault and Battery\n7       Assault and Battery\n8       Assault and Battery\n9       Assault and Battery\n10      Assault and Battery\n11      Assault and Battery\n12      Assault and Battery\n13      Assault and Battery\n14      Assault and Battery\n15      Assault and Battery\n16      Assault and Battery\n17      Assault and Battery\n18      Assault and Battery\n19      Assault and Battery\n20      Assault and Battery\n21      Assault and Battery\n22      Assault and Battery\n23      Assault and Battery\n24      Assault and Battery\n25      Assault and Battery\n26      Assault and Battery\n27      Assault and Battery\n28      Assault and Battery\n29      Assault and Battery\n               ...         \n1263         Weapon Offense\n1264         Weapon Offense\n1265         Weapon Offense\n1266         Weapon Offense\n1267         Weapon Offense\n1268         Weapon Offense\n1269         Weapon Offense\n1270         Weapon Offense\n1271         Weapon Offense\n1272         Weapon Offense\n1273         Weapon Offense\n1274         Weapon Offense\n1275         Weapon Offense\n1276         Weapon Offense\n1277         Weapon Offense\n1278         Weapon Offense\n1279         Weapon Offense\n1280         Weapon Offense\n1281         Weapon Offense\n1282         Weapon Offense\n1283         Weapon Offense\n1284         Weapon Offense\n1285         Weapon Offense\n1286         Weapon Offense\n1287         Weapon Offense\n1288         Weapon Offense\n1289         Weapon Offense\n1290         Weapon Offense\n1291         Weapon Offense\n1292         Weapon Offense\nName: category, Length: 1293, dtype: object'